### ISSUE TITLE
Please Release to a Maven Repo

### ISSUE THREAD

**Issue by GoogleCodeExporter** [npryce/make-it-easy#1]
```
Please consider releasing make-it-easy into a maven2 repository, it makes
life for maven users much simpler.
```

Original issue reported on code.google.com by `cyet...@gmail.com` on 31 Jan 2010 at 10:04

**Comment by npryce** [comment]
I will be publishing the next version to Maven Central.

If you publish your own builds (which I'm happy for people to do) please do not use com.natpryce as the group id. Use your own group id.

**Comment by npryce** [comment]
Done
