### ISSUE TITLE
com.sun.tools.javac.comp.Infer$GraphStrategy$NodeNotFoundException

### ISSUE THREAD

**Issue by wrungel** [npryce/make-it-easy#10]
This is not an error in make-it-easy framework itself but it occurs prevalently when make-it-easy is used with Java 8.
I just want to point to the existing problem. 
I will shortly create a new ticket by OpenJDK bug system: https://bugs.openjdk.java.net/secure/Dashboard.jspa.

There is another problem with JDK 8 compiler which occurs when compiling classes with several nested generic expressions, which is typical when using make-it-easy expressions: the compilation is extremly slow then.

The test project is here:
https://github.com/wrungel/bugs/tree/master/make-it-easy-jdk8-NodeNotFoundException

Java Compiler used: JDK 1.8.45
make-it-easy version: 4.0.0

**Comment by wrungel** [comment]
I have just created a new bug report be Oracle: http://bugreport.java.com/bugreport/
Its Review ID is JI-9021524.

**Comment by npryce** [comment]
Closing because this is not an issue with the Make-it-Easy project.
