### ISSUE TITLE
Getting type safety warning : A generic array of PropertyValue<? super T,?> is created for a varargs parameter

### ISSUE THREAD

**Issue by oliverlockwood** [npryce/make-it-easy#13]
I'm having an issue with make-it-easy 4.0.0; it has been described here:  https://code.google.com/p/make-it-easy/issues/detail?id=5

This old issue in Google Code seems to suggest this could be resolved by suppressing the warnings at source.  Any thoughts on this - has this issue been investigated at all?

Many thanks.

**Comment by npryce** [comment]
I haven't investigated but it looks like the @SafeVarargs annotation would
fix the problem.

**Comment by mwilliamson** [comment]
Isn't this fixed by this commit?

https://github.com/npryce/make-it-easy/commit/06c0a5f4fb84ab2e02240ba19252fe3b41e20f0d

I've been using Jitpack to depend on a later commit than 4.0.0, and it does indeed seem to get rid of the warnings.

**Comment by oliverlockwood** [comment]
@mwilliamson interesting, that does look like it would fix things (though I've yet to try in my explicit case).

Which then begs the question for @npryce - is there any chance of getting a release built which includes that commit?

**Comment by GrzegorzLigas** [comment]
@npryce Hey, any chance to get a release with the commit as per above included, please?

**Comment by bencope** [comment]
Reviving this thread, @npryce can we please get a release with the @SafeVarargs commit included?

**Comment by cregganna** [comment]
+1 for this

**Comment by npryce** [comment]
Done.

**Comment by oliverlockwood** [comment]
@npryce thanks for making the time to get a new release out, much appreciated.  I just removed 20 instances of `@SuppressWarnings("unchecked")` as a result of the new release :grinning:
