### ISSUE TITLE
Sample code link

### ISSUE THREAD

**Issue by GoogleCodeExporter** [npryce/make-it-easy#4]
```
The sample code link to checkout from subversion is broken.  Results in 404 
error.

Ideally a zip file of the sample code would be offered so I don't have to do 
with version control.



```

Original issue reported on code.google.com by `harpark...@gmail.com` on 2 Jun 2010 at 2:01

**Comment by npryce** [comment]
Link fixed.  GitHub lets you download code in zip or tgz format from the Releases tab (https://github.com/npryce/make-it-easy/releases).
